#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";

import minimist from "minimist";

import { discoverExtensions } from "./discovery";
import { createNexusClient } from "./nexusClient";
import { resolveFixtures } from "./resolveFixtures";
import type { IFixture } from "./types";

// pnpm forwards a literal "--" separator into argv; minimist treats "--" as
// stop-parsing, so strip it before parsing flags.
const argv = minimist(process.argv.slice(2).filter((a) => a !== "--"));
const all = argv.all === true || argv.all === "true";
const single = typeof argv.game === "string" ? argv.game : undefined;
const list = typeof argv.games === "string" ? argv.games.split(",") : undefined;

if (!all && !single && !list) {
  console.error("Usage: --all | --game <id> | --games <a,b,c>");
  process.exit(1);
}

const apiKey = process.env.NEXUS_API_KEY ?? "";
if (!apiKey) {
  console.error("NEXUS_API_KEY environment variable is required.");
  process.exit(1);
}

const packageRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(__dirname, "../../..");
const fixturesDir = path.join(packageRoot, ".fixtures");

const requested = all ? null : single ? [single] : (list ?? []);

void main();

async function main(): Promise<void> {
  const exts = discoverExtensions(repoRoot);
  const selected =
    requested === null
      ? exts
      : exts.filter(
          (e) =>
            requested.includes(e.packageName) ||
            requested.some((g) => e.packageDir.endsWith(`/${g}`)),
        );
  if (selected.length === 0) {
    console.error(`No opted-in extensions matched: ${requested?.join(", ") ?? "(all)"}`);
    process.exit(1);
  }

  fs.rmSync(fixturesDir, { recursive: true, force: true });
  fs.mkdirSync(fixturesDir, { recursive: true });

  const client = createNexusClient(apiKey);
  for (const found of selected) {
    const descriptor = await loadDescriptor(found.packageDir);
    console.log(`[${descriptor.gameId}] resolving fixtures…`);
    const fixtures = await resolveFixtures(client, descriptor);
    for (const fx of fixtures) {
      const stubPath = path.join(
        fixturesDir,
        `${descriptor.gameId}-${fx.modId}-${fx.fileId}.test.ts`,
      );
      fs.writeFileSync(stubPath, generateStub(found.packageDir, descriptor.gameId, fx));
    }
    console.log(`[${descriptor.gameId}] wrote ${fixtures.length} fixture stubs`);
  }

  const vitestConfig = path.join(packageRoot, "vitest.fixtures.config.ts");
  const result = spawnSync("pnpm", ["exec", "vitest", "run", "--config", vitestConfig], {
    stdio: "inherit",
    cwd: packageRoot,
  });
  process.exit(result.status ?? 1);
}

/**
 * Light loader for an extension's test-descriptor. Skips index.ts so we don't
 * pull `vortex-api` (which under tsx outside vitest may try to load Electron).
 */
async function loadDescriptor(extensionDir: string): Promise<any> {
  const mod = await import(path.join(extensionDir, "src", "test-descriptor.ts"));
  if (!mod.testDescriptor) {
    throw new Error(
      `Extension ${extensionDir} src/test-descriptor.ts has no testDescriptor export`,
    );
  }
  return mod.testDescriptor;
}

function generateStub(extensionDir: string, gameId: string, fx: IFixture): string {
  const label = `${gameId} > modId=${fx.modId} fileId=${fx.fileId}`;
  return `// auto-generated by @vortex/game-extension-test; do not edit
import { test } from "vitest";
import { runOneFixture } from "../src/runOneFixture";
test(${JSON.stringify(label)}, async () => {
  await runOneFixture({
    extensionDir: ${JSON.stringify(extensionDir)},
    fixture: ${JSON.stringify(fx)},
  });
});
`;
}
